import icons from "./icons";

const popular_jobs = [
  {
    id: "popular_job01",
    url: icons.google,
    name: "Google",
    job: "Lead Product Manager",
    salary: "$8k",
    type: "Full Time",
    location: "Tokyo, Japan",
    time: "24h",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of techical product management experience such as creating strategic product roadmaps and working with cross-functional teams to define and implement product vision",
      "Experience driving product vision, go-to-market strategy, and design discussions",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
    ],
    aboutJob: [
      "At Google, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a Product Manager who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Google aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
    ],
  },
  {
    id: "popular_job02",
    url: icons.spotify,
    name: "Spotify",
    job: "Senior UI/UX Designer",
    salary: "$5k",
    type: "Full Time",
    location: "New York, USA",
    time: "4d",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
    ],
  },
  {
    id: "popular_job03",
    url: icons.figma,
    name: "Figma",
    job: "UI/UX Designer",
    salary: "$8k",
    type: "Full Time",
    location: "New York, USA",
    time: "6d",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
    ],
  },
  {
    id: "popular_job04",
    url: icons.linkedin,
    name: "Linkedin",
    job: "Frontend Developer",
    salary: "$8k",
    type: "Full Time",
    location: "London, UK",
    time: "1w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job05",
    url: icons.apple,
    name: "Apple",
    job: "Senior Software Engineer",
    salary: "$12k",
    type: "Full Time",
    location: "California, USA",
    time: "1w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job06",
    url: icons.microsoft,
    name: "Microsoft",
    job: "UX Design Lead",
    salary: "$6k",
    type: "Part Time",
    location: "Berlin, Germany",
    time: "1w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job07",
    url: icons.twitter,
    name: "Twitter",
    job: "Backend Developer",
    salary: "$18k",
    type: "Full Time",
    location: "Silicon Valley, USA",
    time: "2w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job08",
    url: icons.wattpad,
    name: "Wattpad",
    job: "UI/UX Intern",
    salary: "$5k",
    type: "Internship",
    location: "New York, USA",
    time: "2w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job09",
    url: icons.slack,
    name: "Slack",
    job: "UI/UX Designer",
    salary: "$8k",
    type: "Full Time",
    location: "Tokyo, Japan",
    time: "2w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job10",
    url: icons.twitch,
    name: "Twitch",
    job: "MERN Developer",
    salary: "$11k",
    type: "Full Time",
    location: "Paris, France",
    time: "2w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job11",
    url: icons.google,
    name: "Google",
    job: "User Experience Researcher",
    salary: "$15k",
    type: "Full Time",
    location: "Dubai, UAE",
    time: "3w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
  {
    id: "popular_job12",
    url: icons.amazon,
    name: "Amazon",
    job: "React Native Developer",
    salary: "$20k",
    type: "Full Time",
    location: "San Francisco, USA",
    time: "3w",
    qualifications: [
      "Bachelor's degree or equivalent practical experience",
      "3+ years of UI/UX design experience",
      "Experience with product management tools such as Jira, Confluence, and Agile",
      "Team player with excellent communication skills",
      "Knowledge of HTML5, CSS3, JavaScript, jQuery, React, Redux, Node.js, Express, MongoDB, MySQL, and other technologies.",
    ],
    aboutJob: [
      "At Spotify, we put our users first. The world is always changing so we need Product Managers who are continuously adapting and excited to work on products that affect millions of people every day.",
      "We are looking for a UI/UX designer who is passionate about building products that matter. You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "You will work with a team of Product Managers, Product Designers, and Product Engineers to create and implement products that matter to our users.",
      "Spotify aims to build products that organize the world's information and make it universally accessible to our users. As a Product Manager at Google, you could be working on new technologies, platforms, consumer facing products, and/or enterprise systems. The end goal will be to match you with the team that best aligns with your interests, experience, and where you will have the most impact.",
    ],
    responsibilities: [
      "Define, lead, and execute a holistic strategy to meet our goals; collaborate across regions, product areas and functions.",
      "Work across a cross-functional team (UX, UXR, ENG, Sales and others) to make these ideas successful. Work effectively with the dedicated engineering team and partner teams within Google.",
      "Speak at marketing events. Meet customers to gather feedback and to present roadmaps.",
      "Synthesize and drive product strategy from interactions with customers, business stakeholders, legal and policy teams; build and manage an actionable product roadmap.",
      "Launch solutions that demonstrate Google's products and solve customer problems.",
      "Work with the engineering team to build and maintain the frontend of the product.",
    ],
  },
];

export { popular_jobs };
