import icons from "./icons";

const popular_jobs = [
  {
    id: "popular_job01",
    url: icons.google,
    name: "Google",
    job: "Lead Product Manager",
    salary: "$8k",
    type: "Full Time",
    location: "Tokyo, Japan",
  },
  {
    id: "popular_job02",
    url: icons.spotify,
    name: "Spotify",
    job: "Senior UI/UX Designer",
    salary: "$5k",
    type: "Full Time",
    location: "New York, USA",
  },
  {
    id: "popular_job03",
    url: icons.figma,
    name: "Figma",
    job: "UI/UX Designer",
    salary: "$8k",
    type: "Full Time",
    location: "New York, USA",
  },
  {
    id: "popular_job04",
    url: icons.linkedin,
    name: "Linkedin",
    job: "Frontend Developer",
    salary: "$8k",
    type: "Full Time",
    location: "London, UK",
  },
  {
    id: "popular_job05",
    url: icons.apple,
    name: "Apple",
    job: "Senior Software Engineer",
    salary: "$12k",
    type: "Full Time",
    location: "California, USA",
  },
  {
    id: "popular_job06",
    url: icons.microsoft,
    name: "Microsoft",
    job: "UX Design Lead",
    salary: "$6k",
    type: "Part Time",
    location: "Berlin, Germany",
  },
  {
    id: "popular_job07",
    url: icons.twitter,
    name: "Twitter",
    job: "Backend Developer",
    salary: "$18k",
    type: "Full Time",
    location: "Silicon Valley, USA",
  },
  {
    id: "popular_job08",
    url: icons.wattpad,
    name: "Wattpad",
    job: "UI/UX Intern",
    salary: "$5k",
    type: "Internship",
    location: "New York, USA",
  },
  {
    id: "popular_job09",
    url: icons.slack,
    name: "Slack",
    job: "Full time UI/UX Designer",
    salary: "$8k",
    type: "Full Time",
    location: "Tokyo, Japan",
  },
  {
    id: "popular_job10",
    url: icons.twitch,
    name: "Twitch",
    job: "MEAN Stack Developer",
    salary: "$11k",
    type: "Full Time",
    location: "Paris, France",
  },
  {
    id: "popular_job11",
    url: icons.google,
    name: "Google",
    job: "User Experience Researcher",
    salary: "$15k",
    type: "Full Time",
    location: "Dubai, UAE",
  },
  {
    id: "popular_job12",
    url: icons.amazon,
    name: "Amazon",
    job: "React Native Developer",
    salary: "$20k",
    type: "Full Time",
    location: "San Francisco, USA",
  },
];

export { popular_jobs };
